name: Update compatible version

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number'
        required: true
        default: '1.3.2'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Invoke deployment hook
        uses: distributhor/workflow-webhook@v3
        with:
          webhook_url: https://transrepo.ziyuesinicization.site/cbue
          data: '{ "master_branch": "main", "compatible": "${{ github.event.inputs.version }}" }'
          
